# Ordem de carga do ModSecurity + OWASP CRS 4.
Include /etc/nginx/modsec/modsecurity.conf
Include /etc/nginx/modsec/crs-setup.conf
Include /etc/nginx/modsec/exclusoes.conf
Include /etc/nginx/modsec/crs/plugins/*-config.conf
Include /etc/nginx/modsec/crs/plugins/*-before.conf
Include /etc/nginx/modsec/crs/rules/*.conf
Include /etc/nginx/modsec/crs/plugins/*-after.conf
